### ISSUE TITLE
small detail. But where is the beautiful icon?!

### ISSUE THREAD

**Issue by wwwonka** [MoralAlberto/Slackfari#10]
I've noticed the icon appearing in this image : https://github.com/MoralAlberto/Send-It-for-Slack/blob/master/Assets/delete-team.gif

is actually not the one in the repo's assets or the app on the mac app store... Do you think you can bring the slack logo back? My Safari toolbar would only be greater!

thank you any way, sharing links to slack has been a feature ive been hoping for quite a long time on mac.

**Comment by MoralAlberto** [comment]
I would like it! but, in order to submit the app on the App Store, the apple reviewers rejected multiple times my app because the logo was very similar to Slack icon (I tried different options). I will try to improve the current icon.

thanks for your feedback!

**Comment by wwwonka** [comment]
Hell.
I've been using Slack for more than 2 years and still cant beleive the sharing option is not yet integrated into OS X; and then you come along.
Good for us you aim towards good taste!

Ok.

Let metry to actually help... ! ..m'yeah, here: https://slack.com/brand-guidelines

![slacklogo_forbiddenspecies](https://user-images.githubusercontent.com/16738328/33466912-0a46437e-d61f-11e7-8901-d68fbf732b11.PNG)

...The problem was probably your submission was in fact tresspassing the law and you were using the sacred Slack logo!

..'Never had to deal directly with  as a content creator, but one thing they taught me over time is that coding software might feel complex at times,  but in the end it won't ever be as filled with mysterious rules and silently regulated as a company branding . . . Good luck !
