### ISSUE TITLE
Is this app still supported

### ISSUE THREAD

**Issue by jrich8573** [MoralAlberto/Slackfari#11]
@MoralAlberto is this app still supported? When you believe the next version will be released. 

Cheers!

**Comment by MoralAlberto** [comment]
Hello! sorry, but this app is not supported. I'm currently working on a big update, with a macOS app, and some cool features: you can create and share a URL with a list of cool articles to share with your coworkers, authentication with Slack without creating a Token manually, adding multiple Slack Teams, share links on Twitter, stats, etc

if you want, I will let you know when I release the new version, if you want to take a look (screenshots)
https://www.albertomoral.com/readit

And also, an example of sharing a URL with some articles:
https://readlater-80c6b.firebaseapp.com/?name=BFTYVZEOr9SEhFr38S5urCsJLEv2&tag=Swift

thank you!

**Comment by jrich8573** [comment]
@MoralAlberto thank you for quick response. I will certainly look through the links providing. 

Thank you again.
